### ISSUE TITLE
Canvis de literals i millores en la consulta de remeses i els detalls

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/notib#407]
- [x] Modificar literals d'òrgan gestor en la consulta de remeses #402
- [x] Modificar el títol del detalls d'una Comunicació #403
- [x] Modificacions detalls d'una notificació/comunicació #404
- [x] Modificar literal "Òrgan gestor" en el formulari d'enviament #405 
- [x] Afegir icona al camp Estat dels detalls d'una notificació/comunicació #406
- [x] Afegir l'estat en les dades de l'enviament dins del detall de la notificació #410
